// <auto-generated />
using System;
using JobFinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobFinder.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231227071702_seeding")]
    partial class seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobFinder.Entities.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverLetter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("bit");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("JobSeekerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("JobSeekerId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("JobFinder.Entities.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, Anytown, CA 12345",
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6466),
                            Email = "info@acme.com",
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Acme Corporation",
                            PhoneNumber = "1-800-555-1212",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Elm St, Business City, NY 54321",
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6468),
                            Email = "contact@globex.com",
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Globex Corporation",
                            PhoneNumber = "1-888-555-2323",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Address = "456 Elm St, Business City, NY 54321",
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6470),
                            Email = "contact@microsoft.com",
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Microsoft",
                            PhoneNumber = "1-888-555-2323",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Address = "456 Elm St, Business City, NY 54321",
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6471),
                            Email = "contact@uber.com",
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Uber",
                            PhoneNumber = "1-888-555-2323",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Address = "789 Tech St, Silicon Valley, CA 98765",
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6473),
                            Email = "support@initech.com",
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Initech",
                            PhoneNumber = "1-877-555-3434",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("JobFinder.Entities.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("JobFinder.Entities.Entities.JobSeeker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFresh")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("JobSeekers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6495),
                            Email = "john.doe@example.com",
                            IsFresh = false,
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Doe",
                            UserId = 6,
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6497),
                            Email = "jane.smith@example.com",
                            IsFresh = true,
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane Smith",
                            UserId = 7,
                            YearsOfExperience = 0
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6498),
                            Email = "bob.johnson@example.com",
                            IsFresh = false,
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bob Johnson",
                            UserId = 8,
                            YearsOfExperience = 7
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6499),
                            Email = "alice.williams@example.com",
                            IsFresh = true,
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Alice Williams",
                            UserId = 9,
                            YearsOfExperience = 0
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6501),
                            Email = "random@example.com",
                            IsFresh = true,
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Random",
                            UserId = 10,
                            YearsOfExperience = 0
                        });
                });

            modelBuilder.Entity("JobFinder.Entities.Entities.UserManagement.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.Property<int?>("Timer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModificationDate = new DateTime(2023, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "JobSeeker",
                            RoleType = 0
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModificationDate = new DateTime(2023, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Employer",
                            RoleType = 0
                        });
                });

            modelBuilder.Entity("JobFinder.Entities.Entities.UserManagement.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsCompany")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6225),
                            Email = "info@acme.com",
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "password",
                            isCompany = true
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6236),
                            Email = "contact@globex.com",
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "password",
                            isCompany = true
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6237),
                            Email = "contact@microsoft.com",
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "password",
                            isCompany = true
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6239),
                            Email = "contact@uber.com",
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "password",
                            isCompany = true
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6240),
                            Email = "support@initech.com",
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "password",
                            isCompany = true
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6241),
                            Email = "john.doe@example.com",
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "password",
                            isCompany = false
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6242),
                            Email = "jane.smith@example.com",
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "password",
                            isCompany = false
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6293),
                            Email = "bob.johnson@example.com",
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "password",
                            isCompany = false
                        },
                        new
                        {
                            Id = 9,
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6294),
                            Email = "alice.williams@example.com",
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "password",
                            isCompany = false
                        },
                        new
                        {
                            Id = 10,
                            CreationDate = new DateTime(2023, 12, 27, 10, 17, 2, 274, DateTimeKind.Local).AddTicks(6295),
                            Email = "random@example.com",
                            ModificationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "password",
                            isCompany = false
                        });
                });

            modelBuilder.Entity("JobFinder.Entities.Entities.UserManagement.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("JobFinder.Entities.Entities.Application", b =>
                {
                    b.HasOne("JobFinder.Entities.Entities.Job", "Job")
                        .WithMany("Applications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JobFinder.Entities.Entities.JobSeeker", "JobSeeker")
                        .WithMany("Applications")
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("JobSeeker");
                });

            modelBuilder.Entity("JobFinder.Entities.Entities.Company", b =>
                {
                    b.HasOne("JobFinder.Entities.Entities.UserManagement.User", "User")
                        .WithOne("Company")
                        .HasForeignKey("JobFinder.Entities.Entities.Company", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobFinder.Entities.Entities.Job", b =>
                {
                    b.HasOne("JobFinder.Entities.Entities.Company", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("JobFinder.Entities.Entities.JobSeeker", b =>
                {
                    b.HasOne("JobFinder.Entities.Entities.UserManagement.User", "User")
                        .WithOne("JobSeeker")
                        .HasForeignKey("JobFinder.Entities.Entities.JobSeeker", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobFinder.Entities.Entities.UserManagement.UserRole", b =>
                {
                    b.HasOne("JobFinder.Entities.Entities.UserManagement.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("JobFinder.Entities.Entities.UserManagement.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobFinder.Entities.Entities.Company", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("JobFinder.Entities.Entities.Job", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("JobFinder.Entities.Entities.JobSeeker", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("JobFinder.Entities.Entities.UserManagement.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("JobFinder.Entities.Entities.UserManagement.User", b =>
                {
                    b.Navigation("Company")
                        .IsRequired();

                    b.Navigation("JobSeeker")
                        .IsRequired();

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
